# Stage 1
FROM node:12 AS base-build

WORKDIR /app

# COPY package.json index.js ./
COPY package.json index.js /app/

RUN npm install

# Stage 2
FROM node:12

COPY --from=base-build /app /

EXPOSE 3000

CMD ["index.js"]
